# Yigit Erkal
# 21601521

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: ${{ matrix.python-version }} version-control
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: pytest and pip installation
      run: |
        python -m pip install pytest
        pip install -r requirements.txt
        pytest
      
  build-publish:
      needs: [test]
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'push' }}
      steps:
      - name: Build,install pip
        run: |
              touch pyproject.toml
              pip install build
              python -m build
      - name: Publishing it to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{secrets.SECRET_TOKEN}}

            

      
     

      
        
